# Generated by Django 2.2.3 on 2019-07-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_auto_20190708_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='action',
            field=models.CharField(default='register', max_length=100),
            preserve_default=False,
        ),
    ]
