# Generated by Django 2.2.3 on 2019-07-16 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190710_1004'),
        ('myuser', '0007_verifycode_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCollectBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myuser.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='collect_blog',
            field=models.ManyToManyField(related_name='collectors', through='myuser.ProfileCollectBlog', to='blog.Blog'),
        ),
    ]
