# Generated by Django 2.2.3 on 2019-07-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_auto_20190716_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='collect_blog',
        ),
        migrations.DeleteModel(
            name='ProfileCollectBlog',
        ),
    ]
