# Generated by Django 2.2.3 on 2019-07-23 17:40

from django.db import migrations, models
import myuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0009_auto_20190717_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=myuser.models.user_directory_path),
        ),
    ]
