# Generated by Django 2.2.3 on 2019-07-24 10:12

from django.db import migrations, models
import myuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0010_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=myuser.models.user_directory_path),
        ),
    ]
