# Generated by Django 2.2.3 on 2019-07-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_comment_is_first_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='first_comment',
            new_name='parent_comment',
        ),
    ]
