# Generated by Django 2.2.3 on 2019-07-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20190711_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='top_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descendants', to='comment.Comment'),
        ),
    ]
