# Generated by Django 2.2.3 on 2019-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
