# Generated by Django 2.2.3 on 2019-07-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0002_like_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='total',
        ),
    ]
